import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import React, { useEffect, useState } from "react";
import { Button } from "../components/Button";

type Pokemon = {
  id: number,
  name: string,
  imageUrl: string
}

const Home: NextPage = () => {
  const [pokemonName, setPokemonName] = useState("");
  const [pokemons, setPokemons] = useState<Pokemon[]>([]);
  const [loading, setLoading] = useState("");

  const handleChange = (event: React.ChangeEvent<HTMLInputElement>) =>
    setPokemonName(event.target.value.toLowerCase());

  const catchPokemon = async () => {
    if (!pokemonName) return;

    setLoading("catching...");

    const response = await fetch("/api/pokemon", {
      method: "POST",
      body: JSON.stringify({ name: pokemonName }),
      headers: { "Content-Type": "application/json" },
    });

    const resJSON = await response.json();
    if (response.ok) {
      await fetchPokemons();
      console.log({ resJSON });
    } else {
      await fetchPokemons()
    }
  };

  const fetchPokemons = async () => {
    setLoading("Fetching...");
    const response = await fetch("/api/pokemon");

    if (response.ok) {
      const { data } = await response.json();
      setLoading("");
      setPokemons(data);
    } else {
      console.log("Error fetch the data");
    }
  };

  useEffect(() => {
    fetchPokemons();
  }, []);

  return (
    <>
      <Head>
        <title>Pokedex</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center gap-12 px-4 py-8 ">
          <h1 className="text-5xl font-black text-white">
            Which Pokemon would you like to catch?
          </h1>
          <span className="text-gray-300">
            {pokemons.length} have been caught
          </span>
          <input
            onChange={handleChange}
            value={pokemonName}
            className="rounded-full bg-[#532c89] py-2 px-4 text-center text-xl md:text-5xl font-light tracking-tight text-white"
          />
        </div>
        <Button onClick={catchPokemon} isLoading={loading}>Atrapar</Button>
        <div className="mt-6 flex w-full px-10 md:max-w-[70rem] flex-wrap gap-4">
          {pokemons.map((pokemon) => (
            <div
              key={pokemon.id}
              className="mt-4 flex flex-col items-center justify-center rounded-lg bg-white shadow-md shadow-white hover:scale-105 hover:cursor-pointer"
            >
              <Image
                src={pokemon.imageUrl}
                alt={pokemon.name}
                width={150}
                height={150}
              />
              <p className="font-bold">{pokemon.name.toUpperCase()}</p>
            </div>
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
